### ISSUE TITLE
vatex复现报错No such file or directory: '/ai/swxdisk/data/vatex/test_list.txt'

### ISSUE THREAD

**Issue by dmcsy** [cheetah003/HMMC#1]
你好，在使用vatex数据集复现代码的时候报错如下：
![image](https://github.com/cheetah003/HMMC/assets/102478865/5b1469c2-11a9-4003-8a38-1b54f399b304)
具体为：
```
Traceback (most recent call last):
  File "main_task_retrieval.py", line 649, in <module>
    main()
  File "main_task_retrieval.py", line 576, in main
    test_dataloader, test_length = DATALOADER_DICT[args.dataset]["test"](args, tokenizer)
  File "/home/weixiang/code/HMMC-main/dataloaders/dataloader.py", line 158, in dataloader_vatex_test
    vatex_testset = VATEX_multi_sentence_dataLoader(root='/ai/swxdisk/data/vatex/vatex_lmdb', language=args.language,
  File "/home/weixiang/code/HMMC-main/dataloaders/dataloader_vatex_retrieval.py", line 67, in __init__
    with open(video_id_path_dict[self.subset], 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/ai/swxdisk/data/vatex/test_list.txt'
```
请问这里的test_list.txt还有val_list.txt、train_list.txt这几个文件在哪里可以获取呢？文档里的下载链接中都只有json文件，没找到txt文件，可以分享一下吗？谢谢！

**Comment by cheetah003** [comment]
你好，txt文件放在tool/vatex_txt目录下了，你pull下就行

**Comment by dmcsy** [comment]
不好意思，刚看见消息，好的谢谢您!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月1日(周三) 下午3:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cheetah003/HMMC] vatex复现报错No such file or directory: '/ai/swxdisk/data/vatex/test_list.txt' (Issue #1)




 
Closed #1 as completed.
